### PR TITLE
Codemod: Converts 'es2015-i18n-tag' JSON format to PO

### PR DESCRIPTION
**Pull request by adamsoderstrom**
- chore(es2015-i18n-tag-to-po): initial commit
- chore(toPo): add line breaks between "file path" objects
- chore(toPo): update package.json
- chore(toPo): add placeholder markdown files
- chore(toPo): add 'src/index.ts'

### CODE REVIEW

**Comment by adamsoderstrom** [comment]
*Adding as draft*

Would need some assistance here, @maeertin.

Would want to try this out locally via `yalc` and something similar to `npx`, but don't know how to proceed.

Do you have any pointers?

I'm picturing something similar to the setup in `@noaignite/create-app`. 🤔

**Comment by maeertin** [comment]
Is this package still relevant @adamsoderstrom now that we dropped CIA?

**Comment by adamsoderstrom** [comment]
No @maeertin

**Comment by maeertin** [comment]
Closing PR as no longer relevant.

**Pull request closed without merging**
