### PR TITLE
chore: add initial version of `.nvmrc`

### PR DESCRIPTION
**Pull request by adamsoderstrom**
So a contributor could run `nvm use` in the root of the repository.

### CODE REVIEW

**Comment by adamsoderstrom** [comment]
We should probably add a `CONTRIBUTING.md`

**Comment by adamsoderstrom** [comment]
**todo:** Bump all the packages to conform to (at least) Node v20.

**Comment by maeertin** [comment]
> **todo:** Bump all the packages to conform to (at least) Node v20 (#154). This should be done in this PR.

Let's do this as a separate PR for the individual packages as this would mean breaking changes for each of them.

**Review by maeertin — APPROVED** [review]
LGTM

**Pull request merged**
