### PR TITLE
feat(centra-types, react-centra-checkout): bump minimum engine node version from 14 to 20

### PR DESCRIPTION
**Pull request by maeertin**
BREAKING CHANGE

### CODE REVIEW

**Comment by maeertin** [comment]
Addresses ticket #154

**Review by adamsoderstrom — COMMENTED** [review]
LGTM!
...But maybe on hold until necessary?

**Comment by maeertin** [comment]
> LGTM! ...But maybe on hold until necessary?

Agreed :)

[feat(react-centra-checkout): convert all default exports to named exports](https://github.com/noaignite/accelerator/pull/217)
This PR is also breaking and fits nicely in with this one as a major

**Review by adamsoderstrom — APPROVED** [review]
LGTM!

**Pull request merged**
